### ISSUE TITLE
Something wrong with editing

### ISSUE THREAD

**Issue by kjcole** [mjsir911/ConfigMaker#10]
Try adding a few trials in a single session. Now try editing each one. Now try editing them again. (All within the same run.)

For me, there came a point rather quickly, where choosing an old trial from the ListBox at the bottom of the window failed to work at all.

The cause is probably related to the error:

```
2017-06-11 15:11:44.426 python[1798:79783] modalSession has exited prematurely - check for a reentrant call to endModalSession:
Description:
Program:
```

(I'm guessing the last two lines are actually your debugging code.)

**Comment by mjsir911** [comment]
should be fixed with #12
