### ISSUE TITLE
Check for duplicates within single run

### ISSUE THREAD

**Issue by kjcole** [mjsir911/ConfigMaker#11]
I started creating a trial named "beta test 2" but then decided I wanted to do something else first. So, I closed the window with the red (X) in the upper left corner. Thinking it had not been created -- a good reason for an explicit [Cancel] button -- I created it again.

And the code let me. After some playing and NO saving yet, I've got five identically named trials.

**Comment by mjsir911** [comment]
Will add [Cancel] button, will do identical to (X) button
