### ISSUE TITLE
Local changes to push

### ISSUE THREAD

**Issue by kjcole** [mjsir911/ConfigMaker#36]
I seem to recall that forking ConfigMaker and using pull requests didn't work very well...  I have two commits that only live on the Mac in the lab. (They can probably be combined into one:

1. Enable offset buttons and set value range from **0** to **600000**
2. Change label from "**Offset (sec)**" to "**Offset (ms)**"

**Comment by mjsir911** [comment]
fixed in fa3c47d857a7f031bc3539e3a209ab86736fe32b
